M48
; DRILL file {KiCad 7.0.5} date Wed Sep  6 13:43:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-06T13:43:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X52.578Y-46.609
X52.578Y-145.796
X98.425Y-46.609
X98.425Y-145.796
T2
X54.3Y-41.6
X54.3Y-150.8
X96.7Y-41.6
X96.7Y-150.8
T0
M30
